[
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Clinton Mcclure",
        "fName": "Hannah Mcclure",
        "caseID": "C 00001 AA",
        "caseStatus": "Completed",
        "familyStatus": "Married",
        "mNumber": "+1(201)555-0124",
        "fNumber": "+1(201)555-0124",
        "mEmail": "c.mcclure@example.com",
        "fEmail": "c.mcclure@example.com",
        "mDOB": "40",
        "fDOB": "36",
        "Address": "6391 Elgin St. Celina,Delaware 10299",
        "id": "1"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Lavern Laboy",
        "fName": "Elanor Laboy",
        "caseID": "C 00001 AA",
        "caseStatus": "Completed",
        "familyStatus": "Married",
        "mNumber": "+1(201)555-0124",
        "fNumber": "+1(201)555-0124",
        "mEmail": "c.mcclure@example.com",
        "fEmail": "c.mcclure@example.com",
        "mDOB": "38",
        "fDOB": "32",
        "Address": "6391 Elgin St. Celina,Delaware 10299",
        "id": "2"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Merrill Kervin",
        "fName": "Cyndy Kevin",
        "caseID": "C 00001 AA",
        "caseStatus": "In progress",
        "familyStatus": "Married",
        "mNumber": "+1(201)555-0124",
        "fNumber": "+1(201)555-0124",
        "mEmail": "c.mcclure@example.com",
        "fEmail": "c.mcclure@example.com",
        "mDOB": "40",
        "fDOB": "36",
        "Address": "6391 Elgin St. Celina,Delaware 10299",
        "id": "4"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Daryl Kulilkowski",
        "fName": "Kylee Kulilkowski",
        "caseID": "C 00001 AA",
        "caseStatus": "To do",
        "familyStatus": "Married",
        "mNumber": "+1(201)555-0124",
        "fNumber": "+1(201)555-0124",
        "mEmail": "c.mcclure@example.com",
        "fEmail": "c.mcclure@example.com",
        "mDOB": "40",
        "fDOB": "36",
        "Address": "6391 Elgin St. Celina,Delaware 10299",
        "id": "5"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Daryl Nehlis",
        "fName": "Tynisha Negis",
        "caseID": "C 00001 AA",
        "caseStatus": "To do",
        "familyStatus": "Married",
        "mNumber": "+1(201)555-0124",
        "fNumber": "+1(201)555-0124",
        "mEmail": "c.mcclure@example.com",
        "fEmail": "c.mcclure@example.com",
        "mDOB": "40",
        "fDOB": "36",
        "Address": "6391 Elgin St. Celina,Delaware 10299",
        "id": "6"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Leatrice Handler",
        "fName": "",
        "caseID": "C 00001 AA",
        "caseStatus": "In progress",
        "familyStatus": "Single",
        "mNumber": "+1(201)555-0124",
        "fNumber": "+1(201)555-0124",
        "mEmail": "c.mcclure@example.com",
        "fEmail": "c.mcclure@example.com",
        "mDOB": "40",
        "fDOB": "",
        "Address": "6391 Elgin St. Celina,Delaware 10299",
        "id": "7"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Edgar Torrey",
        "fName": "Annabel Torrey",
        "caseID": "C 00001 AA",
        "caseStatus": "Completed",
        "familyStatus": "Married",
        "mNumber": "+1(201)555-0124",
        "fNumber": "+1(201)555-0124",
        "mEmail": "c.mcclure@example.com",
        "fEmail": "c.mcclure@example.com",
        "mDOB": "40",
        "fDOB": "36",
        "Address": "6391 Elgin St. Celina,Delaware 10299",
        "id": "8"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Willian Sans",
        "fName": "Hena Sans",
        "caseID": "C 00001 AA",
        "caseStatus": "Completed",
        "familyStatus": "Married",
        "mNumber": "+1(201)555-0124",
        "fNumber": "+1(201)555-0124",
        "mEmail": "c.mcclure@example.com",
        "fEmail": "c.mcclure@example.com",
        "mDOB": "40",
        "fDOB": "36",
        "Address": "6391 Elgin St. Celina,Delaware 10299",
        "id": "9"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Will Smith",
        "fName": "Elly Smith",
        "caseID": "C 00001 AA",
        "caseStatus": "In progress",
        "familyStatus": "Married",
        "mNumber": "+1(201)555-0124",
        "fNumber": "+1(201)555-0124",
        "mEmail": "c.mcclure@example.com",
        "fEmail": "c.mcclure@example.com",
        "mDOB": "40",
        "fDOB": "36",
        "Address": "6391 Elgin St. Celina,Delaware 10299",
        "id": "10"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Aniket ",
        "fName": "",
        "caseID": "C 1101 A",
        "caseStatus": "To do",
        "familyStatus": "Single",
        "mNumber": "9999912222",
        "fNumber": "",
        "mEmail": "a@example.com",
        "fEmail": "",
        "mDOB": "23",
        "fDOB": "",
        "Address": "H-42 mall road shimla",
        "id": "11"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Sameer Mishra",
        "fName": "",
        "caseID": "C 1101 A",
        "caseStatus": "In progress",
        "familyStatus": "Single",
        "mNumber": "9999912222",
        "fNumber": "",
        "mEmail": "a@example.com",
        "fEmail": "",
        "mDOB": "22",
        "fDOB": "",
        "Address": "H-42 mall road shimla",
        "id": "12"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Aniket ",
        "fName": "",
        "caseID": "C 1101 A",
        "caseStatus": "To do",
        "familyStatus": "Single",
        "mNumber": "9999912222",
        "fNumber": "",
        "mEmail": "a@example.com",
        "fEmail": "",
        "mDOB": "34",
        "fDOB": "",
        "Address": "buckingham palace",
        "id": "13"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Sameer Mishra",
        "fName": "",
        "caseID": "C 1101 A",
        "caseStatus": "In progress",
        "familyStatus": "Single",
        "mNumber": "9999912222",
        "fNumber": "",
        "mEmail": "samer@example.com",
        "fEmail": "",
        "mDOB": "42",
        "fDOB": "",
        "Address": "H-42 mall road shimla",
        "id": "14"
    },
    {
        "m_pic": "https://pbs.twimg.com/media/FjU2lkcWYAgNG6d.jpg",
        "f_pic": "https://encrypted-tbn0.gstatic.com/imDOBs?q=tbn:ANd9GcRblRXlVkR-RDG9pYSEbJsaEY4i2F3ACD3byg&usqp=CAU",
        "mName": "Angelina White",
        "fName": "",
        "caseID": "C 1000 A",
        "caseStatus": "Completed",
        "familyStatus": "Single",
        "mNumber": "1234567890",
        "fNumber": "",
        "mEmail": "BRAR@gmail.com",
        "fEmail": "",
        "mDOB": "12",
        "fDOB": "",
        "Address": "Kumarswamy layout",
        "id": "15",
    }
]